python train.py \
  -b 1\
  -e 100 \
  -l 0.0002 \
  -r 500 \
  -n 'test_FIVarnet_lrup' \
  -t '/home/Data/train/' \
  -v '/home/Data/val/'\
  --cascade 3\
  --cascade_img 3\
  -f 32\
  --chans 12\
  --sens_chans 6